// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQHWkgTul5nCcDSOxRAffBllUADabIm3o',
    appId: '1:256564576967:android:fb9a8254ce4ccc151bb4e2',
    messagingSenderId: '256564576967',
    projectId: 'adastrip-2ddd3',
    storageBucket: 'adastrip-2ddd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ZI2EXSG32VVNDr-z4hXSucaHL2Tt8fs',
    appId: '1:256564576967:ios:36ab7758dcf6c7091bb4e2',
    messagingSenderId: '256564576967',
    projectId: 'adastrip-2ddd3',
    storageBucket: 'adastrip-2ddd3.firebasestorage.app',
    androidClientId: '256564576967-e3ri4jtj1s5phfpvhf69maq782lgrk75.apps.googleusercontent.com',
    iosClientId: '256564576967-pb9ca6g624oek6mnt1ci5kvabpt17e6b.apps.googleusercontent.com',
    iosBundleId: 'com.adastrip',
  );

}